development/custom-views.md

Add middleView, bottomView, sideView;
Add templates path

Add middleView, bottomView, sideView

---

development/hooks.md

Update hooks.md - grammar fixes

---

i18n/es_ES/user-guide/browser-support.md

New file to save Spanish translations from [This](https://github.com/espocrm/documentation/tree/master/user-guide) folder

ES-browser-support.md

---

i18n/es_ES/user-guide/markdown.md

Spanish translation of [this file](https://github.com/espocrm/documentation/blob/master/user-guide/markdown.md).

Spanish translation of markdown.md file

---

i18n/es_ES/user-guide/stream.md

Spanish translation of [this file](https://github.com/espocrm/documentation/blob/master/user-guide/stream.md). Hope you like it and find it useful too

Spanish translation of stream.md file

---

i18n/pt_BR/administration/apache-server-configuration.md
i18n/pt_BR/administration/b2c.md
i18n/pt_BR/administration/backup-and-restore.md
i18n/pt_BR/administration/bpm.md

pt_BR translation for the administration files: apache-server-configuration.md, b2c.md, backup-and-restore.md and bpm.md. 
All files in the proper directory (https://github.com/espocrm/documentation/tree/master/i18n/pt_BR/administration)

Partial pt_BR translation 4 files (1 partial)

---

i18n/es_ES/development/orm.md

Please check if fields between ('  ') like ('Account') needed to be translated, because I did (seemed logic) but I can put them back again in English if I was mistaken.

Spanish translations of orm.md file

---

i18n/es_ES/administration/troubleshooting.md

Observation: You should check if this paragraph is correct
>They must be 644. If any of those file has permission 664 you need to change it to 644. Use your hosting's control panel or chmod command.
I changed 'file has' for 'files have' because of the 'those' before. But I think that you meant ''If any of those files have NOT permission 664 you need to change it to 644''. I didn´t do any modifications yet, ignore this observation if I was mistaken.

Spanish translation of troubleshooting.md file

---

i18n/id_ID/administration/bpm.md

Translations espoCRM into indonesian Update bpm.md

---

i18n/pt_BR/administration/apache-server-configuration.md
i18n/pt_BR/administration/b2c.md
i18n/pt_BR/administration/backup-and-restore.md
i18n/pt_BR/administration/bpm.md
i18n/pt_BR/administration/email-fetching.md
i18n/pt_BR/administration/emails.md

- Some minor corrections were made on previous files. 
- pt_BR translation for the administration files:: finished bpm.md; email-fetching.md; emails.md.
All files in the proper directory (https://github.com/espocrm/documentation/tree/master/i18n/pt_BR/administration)

pt_BR translation 3 files

---

i18n/tr_TR/administration/apache-server-configuration.md

My first translation, I hope you like.

apache-server-configuration.md(turkish)

---

i18n/tr_TR/administration/b2c.md

b2c.md contiune translation

---

i18n/tr_TR/administration/backup-and-restore.md

if you approve I will continue translating.

backup-and-restore.md(Turkish)

---

i18n/tr_TR/administration/bpm.md

bpm.md (Turkish)

---

i18n/tr_TR/administration/entity-manager.md

I think you can add normalization.

entity-manager.md (Turkish translation)

---

i18n/ceb_PH/administration/bpm.md

Changes made:
* Added Cebuano Translation File to this directory:
1. i18n\ceb_PH\administration\bpm.md

Cebuano Localization #2

---

i18n/tr_TR/administration/extensions.md

Thank you for approved the others.

extensions.md (Turkish)

---

i18n/tr_TR/administration/formula.md

That made me very tough. There were too many code blocks.  :)

formula.md (Turkish)

---

i18n/tr_TR/administration/import.md

import.md (turkish)

---

i18n/bn_BD/administration/b2c.md

Translated 91 words into Bengali and added in the bn-bd file

created b2c.md

---

i18n/id_ID/administration/bpm.md

I re-translate bpm.md file, because the previous translation is very low quality. Almost all words use translator machines and without edits. Also included are some script codes and links that should not be translated.
You can see the difference, thank you.

RE-TRANSLATION of bpm.md file to Indonesian.

---

i18n/tr_TR/user-guide/emails.md

Turkish translation emails.md

---

i18n/tr_TR/administration/installation.md

installation.md

---

i18n/pt_BR/administration/entity-manager.md
i18n/pt_BR/administration/formula.md
i18n/pt_BR/administration/import.md
i18n/pt_BR/administration/installation.md
i18n/pt_BR/administration/layout-manager.md
i18n/pt_BR/administration/ldap-authorization-for-ad.md
i18n/pt_BR/administration/ldap-authorization-for-openldap.md
i18n/pt_BR/administration/ldap-authorization.md
i18n/pt_BR/administration/maps.md
i18n/pt_BR/administration/moving-to-another-server.md
i18n/pt_BR/administration/nginx-server-configuration.md
i18n/pt_BR/administration/nginx-virtual-host.md
i18n/pt_BR/administration/portal.md
i18n/pt_BR/administration/roles-management.md
i18n/pt_BR/administration/server-configuration.md
i18n/pt_BR/administration/troubleshooting.md
i18n/pt_BR/administration/upgrading.md
i18n/pt_BR/administration/workflows.md

* formula.md; import.md fully translated to pt_BR
* uploaded all untranslated files so it's easier to compare modifications
All files in the proper directory: (https://github.com/espocrm/documentation/tree/master/i18n/pt_BR/administration)

pt_BR translation of formula.md and import.md

---

i18n/tr_TR/user-guide/reports.md

Thank you for merged the others.

reports.md (Turkish)

---

i18n/tr_TR/administration/upgrading.md

upgrading.md (Turkish)

---

i18n/vi_VN/user-guide/emails.md
i18n/vi_VN/user-guide/markdown.md
i18n/vi_VN/user-guide/mass-email.md
i18n/vi_VN/user-guide/quotes.md
i18n/vi_VN/user-guide/reports.md

Please help me add these files to prepare for Vietnamese translation in the future

Add original file for translating in the future.

---

i18n/pt_BR/administration/installation.md
i18n/pt_BR/administration/layout-manager.md
i18n/pt_BR/administration/ldap-authorization-for-ad.md
i18n/pt_BR/administration/ldap-authorization-for-openldap.md
i18n/pt_BR/administration/ldap-authorization.md

installation.md; layout-manager.md; ldap-authorization-for-ad.md; ldap-authorization-for-openldap.md; ldap-authorization.md.
All files in the proper directory: (https://github.com/espocrm/documentation/tree/master/i18n/pt_BR/administration)

pt_BR translation of 5 files

---

i18n/tr_TR/administration/portal.md

portal.md (Turkish)

---

i18n/tr_TR/user-guide/browser-support.md
i18n/tr_TR/user-guide/emails.md
i18n/tr_TR/user-guide/mass-email.md

Turkish translation 1111 words

---

i18n/tr_TR/administration/roles-management.md

roles-management.md (Turkish)

---

i18n/tr_TR/administration/moving-to-another-server.md

moving-to-another-server.md (Turkish)

---

i18n/ceb_PH/administration/formula.md
i18n/ceb_PH/administration/nginx-server-configuration.md
i18n/ceb_PH/administration/upgrading.md

Changes made:
1. i18n/ceb_PH/administration/formula.md
2. i18n/ceb_PH/administration/upgrading.md
3. i18n/ceb_PH/administration/nginx-server-configuration.md

Cebuano Localization #3

---

i18n/tr_TR/development/api.md

No description. How are you today?

api.md (Turkish)

---

i18n/tr_TR/administration/workflows.md

No description. Thaks for approve.

workflows.md (Turkish)

---

i18n/it_IT/administration/workflows.md

create worklows into Italian

---

i18n/tl_PH/administration/formula.md
i18n/tl_PH/administration/nginx-server-configuration.md
i18n/tl_PH/administration/upgrading.md

Changes made:
Added Filipino/Tagalog Translation Files to this directory:
- i18n/tl_PH/administration/
1. formula.md
2. nginx-server-configuration.md
3. upgrading.md

Filipino (Tagalog) Localization #3

---

i18n/it_IT/administration/maps.md
i18n/it_IT/administration/moving-to-another-server.md
i18n/it_IT/administration/portal.md
i18n/it_IT/administration/server-configuration.md

All files in the proper directory: (https://github.com/espocrm/documentation/tree/master/i18n/it_IT/administration)

it_IT translation of 4 files

---

i18n/tr_TR/administration/layout-manager.md

layout-manager.md (Turkish)

---

i18n/vi_VN/user-guide/emails.md

Update Vietnamese Translation for emails.md

Update Vietnamese Translation for emails.md

---

i18n/tr_TR/administration/server-configuration.md

server-configuration.md (Turkish)

---

i18n/tr_TR/administration/troubleshooting.md

No description. Thanks for merge.

troubleshooting.md

---

i18n/tr_TR/administration/ldap-authorization.md

ldap-authorization.md (Turkish)

---

i18n/tr_TR/development/workflow-service-actions.md

workflow-service-actions.md (Turkish)

---

i18n/tr_TR/administration/nginx-server-configuration.md

nginx-server-configuration.md (Turkish)

---

i18n/tr_TR/development/custom-field-type.md

custom-field-type.md (Turkish)

---

i18n/pt_BR/administration/roles-management.md
i18n/pt_BR/administration/server-configuration.md

pt_BR translation roles-management.md; server-configuration.md

---

i18n/tr_TR/development/extension-packages.md

extension-packages.md (Turkish)

---

i18n/tr_TR/development/dynamic-forms.md

dynamic-forms.md (Turkish)

---

i18n/pt_BR/administration/troubleshooting.md
i18n/pt_BR/administration/upgrading.md
i18n/pt_BR/administration/workflows.md

troubleshooting.md; upgrading.md; workflows.md
All translation is done. If there is something else I can do to help, please just tell me.

pt_BR translation of 3 final files

---

i18n/ceb_PH/administration/installation.md
i18n/ceb_PH/administration/layout-manager.md
i18n/ceb_PH/administration/ldap-authorization-for-ad.md
i18n/ceb_PH/administration/ldap-authorization-for-openldap.md
i18n/ceb_PH/administration/ldap-authorization.md
i18n/ceb_PH/administration/maps.md

Changes made:
1. i18n/ceb_PH/administration/installation.md
2. i18n/ceb_PH/administration/layout-manager.md
3. i18n/ceb_PH/administration/ldap-authorization-for-ad.md
4. i18n/ceb_PH/administration/ldap-authorization-for-openldap.md
5. i18n/ceb_PH/administration/ldap-authorization.md
6. i18n/ceb_PH/administration/maps.md

Cebuano Localization #5

---

i18n/pt_PT/administration/entity-manager.md

Hi translate this file, and I create also de file this administration/entity-manager.md
I hope I did it right!

Translation to Portuguese file administration/entity-manager.md

---

i18n/pt_PT/administration/emails.md

Hi translate this file, and I create also de file this administration/emails.md.

Translation to Portuguese  file administration/emails.md

---

i18n/pt_PT/administration/backup-and-restore.md

Hi translate this file, and I create also de file administration/ backup-and-restore.md

Translation to Portuguese file backup-and-restore.md

---

i18n/pt_PT/administration/b2c.md

Hi translate this file, and I create also de file administration/b2c.md

Translation to Portuguese file b2c.md

---

i18n/pt_PT/administration/bpm.md

Hi translate this file, and I create also de file administration/ bpm.md

Translation to Portuguese file bpm.md

---

i18n/pt_PT/administration/extensions.md

Hi translate this file, and I create also de file administration/ extensions.md

Translation to Portuguese file extensions.md

---

i18n/sl-SI/administration/apache-server-configuration.md
i18n/sl-SI/administration/installation.md
i18n/sl-SI/administration/nginx-server-configuration.md
i18n/sl-SI/administration/nginx-virtual-host.md
i18n/sl-SI/administration/server-configuration.md

Changes made:
- Added i18n/sl-SI/administratrion
1. apache-server-configuration.md
2. installation.md
3. nginx-server-configuration.md
4. nginx-virtual-host.md
5. server-configuration.md

Slovenian Localization #1

---

i18n/tl_PH/administration/entity-manager.md
i18n/tl_PH/administration/import.md

Changes made:
Added Filipino/Tagalog Translation files:
1. i18n/tl_PH/administration/entity-manager.md
2. i18n/tl_PH/administration/import.md

Filipino (Tagalog) Localization #4

---

i18n/pt_PT/administration/formula.md

Hi translate this file, and I create also de file administration/formula.md

Translation to Portuguese file formula.md

---

i18n/pt_PT/administration/import.md

Hi translate this file, and I create also de file administration/import.md

Translation to Portuguese file import.md

---

i18n/pt_PT/administration/installation.md

Hi translate this file, and I create also de file administration/installation.md

Translation to Portuguese file installation.md

---

i18n/pt_PT/administration/layout-manager.md

Hi translate this file, and I create also de file administration/layout-manager.md

Translation to Portuguese file layout-manager.md

---

i18n/pt_PT/administration/roles-management.md

Hi translate this file, and I create also de file administration/roles-management.md

Translation to Portuguese file roles-management.md

---

i18n/pt_PT/administration/maps.md

Hi translate this file, and I create also de file administration/maps.md

Translation to Portuguese file maps.md

---

i18n/pt_PT/administration/portal.md

Hi translate this file, and I create also de file administration/ portal.md

Translation to Portuguese file portal.md

---

i18n/pt_PT/administration/workflows.md

Hi translate this file, and I create also de file administration/workflows.md

Translation to Portuguese file workflows.md

---

i18n/pt_PT/administration/ldap-authorization-for-ad.md

Hi translate this file, and I create also de file administration/ldap-authorization-for-ad.md

Translation to Portuguese file ldap-authorization-for-ad.md

---

i18n/pt_PT/administration/ldap-authorization-for-openldap.md

Hi translate this file, and I create also de file administration/ldap-authorization-for-openldap.md

Translation to Portuguese file ldap-authorization-for-openldap.md

---

i18n/pt_PT/administration/ldap-authorization.md

Hi translate this file, and I create also de file administration/ldap-authorization.md

Translation to Portuguese file ldap-authorization.md

---

i18n/pt_PT/administration/upgrading.md

Hi translate this file, and I create also de file administration/upgrading.md

Translation to Portuguese file upgrading.md

---

i18n/pt_PT/administration/moving-to-another-server.md

Hi translate this file, and I create also de file administration/moving-to-another-server.md

Translation to Portuguese file moving-to-another-server.md

---

i18n/pt_PT/administration/nginx-server-configuration.md

Hi translate this file, and I create also de file administration/nginx-server-configuration.md

Translation to Portuguese file nginx-server-configuration.md

---

i18n/pt_PT/administration/nginx-virtual-host.md

Hi translate this file, and I create also de file administration/nginx-virtual-host.md

Translation to Portuguese file nginx-virtual-host.md

---

i18n/pt_PT/administration/server-configuration.md

Hi translate this file, and I create also de file administration/server-configuration.md

Translation to Portuguese file server-configuration.md

---

i18n/pt_PT/user-guide/markdown.md

Hi translate this file, and I create also de file user-guide/markdown.md

Translation to Portuguese file markdown.md

---

i18n/pt_PT/user-guide/mass-email.md

Hi translate this file, and I create also de file mass-email.md

Translation to Portuguese file mass-email.md

---

i18n/pt_PT/user-guide/stream.md

Hi translate this file, and I create also de file user-guide/stream.md

Translation to Portuguese file stream.md

---

i18n/pt_PT/administration/troubleshooting.md

Hi translate this file, and I create also de file administration/troubleshooting.md

Translation to Portuguese file troubleshooting.md

---

i18n/pt_PT/user-guide/quotes.md

Hi translate this file, and I create also de file user-guide/quotes.md

Translation to Portuguese file quotes.md

---

i18n/ceb_PH/administration/moving-to-another-server.md
i18n/ceb_PH/administration/nginx-virtual-host.md
i18n/ceb_PH/administration/portal.md
i18n/ceb_PH/administration/roles-management.md

Changes made:
1. i18n/ceb_PH/administration/moving-to-another-server.md
2. i18n/ceb_PH/administration/nginx-virtual-host.md
3. i18n/ceb_PH/administration/portal.md
4. i18n/ceb_PH/administration/roles-management.md

Cebuano Localization #6

---

i18n/pt_PT/user-guide/reports.md

Hi translate this file, and I create also de file user-guide/reports.md

Translation to Portuguese file reports.md

---

i18n/pt_BR/user-guide/browser-support.md

Hi translate this file, and I create also de file user-guide/browser-support.md

pt_BR translation of file browser-support.md

---

i18n/pt_BR/user-guide/emails.md

Hi translate this file, and I create also de file user-guide/emails.md

pt_BR translation of file emails.md

---

i18n/pt_BR/user-guide/markdown.md

Hi translate this file, and I create also de file user-guide/markdown.md

pt_BR translation of file markdown.md

---

i18n/pt_BR/user-guide/mass-email.md

Hi translate this file, and I create also de file user-guide/mass-email.md

pt_BR translation of file mass-email.md

---

i18n/id_ID/administration/import.md

New translation (correct word)

Indonesian translation of import.md

---

i18n/pt_BR/user-guide/quotes.md

Hi translate this file, and I create also de file user-guide/quotes.md

pt_BR translation of file quotes.md

---

i18n/pt_BR/user-guide/stream.md

Hi translate this file, and I create also de file user-guide/stream.md

pt_BR translation of file stream.md

---

i18n/pt_BR/user-guide/reports.md

Hi translate this file, and I create also de file user-guide/reports.md

pt_BR translation of file reports.md

---

i18n/ceb_PH/administration/server-configuration.md
i18n/ceb_PH/administration/troubleshooting.md
i18n/ceb_PH/administration/workflows.md

Changes made:
Added Cebuano Translation Files to this directory:
1. i18n/ceb_PH/administration/server-configuration.md
2. i18n/ceb_PH/administration/troubleshooting.md
3. i18n/ceb_PH/administration/workflows.md

Cebuano Localization #7

---

i18n/pt_BR/development/api.md

Hi translate this file, and I create also de file development/api.md

pt_BR translation of file api.md

---

i18n/pt_BR/development/custom-field-type.md

Hi translate this file, and I create also de file development/custom-field-type.md

pt_BR translation of file custom-field-type.md

---

i18n/pt_BR/development/custom-views.md

Hi translate this file, and I create also de file development/custom-views.md

pt_BR translation of file custom-views.md

---

i18n/pt_PT/development/custom-field-type.md

Hi translate this file, and I create also de file development/custom-field-type.md

pt_PT translation of file custom-field-type.md

---

i18n/pt_PT/development/api.md

Hi translate this file, and I create also de file development/api.md

pt_PT translation of file api.md

---

i18n/sl-SI/administration/bpm.md

Slovenian Localization #4

---

i18n/pt_PT/development/custom-views.md

Hi translate this file, and I create also de file development/custom-views.md

pt_PT translation of file custom-views.md

---

i18n/tl_PH/administration/moving-to-another-server.md
i18n/tl_PH/administration/nginx-virtual-host.md
i18n/tl_PH/administration/portal.md
i18n/tl_PH/administration/roles-management.md

Changes made:
1. i18n/tl_PH/administration/moving-to-another-server.md
2. i18n/tl_PH/administration/nginx-virtual-host.md
3. i18n/tl_PH/administration/portal.md
4. i18n/tl_PH/administration/roles-management.md

Filipino (Tagalog) Localization #6

---

i18n/ru_RU/administration/user-guide/quotes.md

Translate into russian quotes.md 145 words

---

i18n/pt_PT/development/dynamic-forms.md

Hi translate this file, and I create also de file development/dynamic-forms.md

pt_PT translation of file dynamic-forms.md

---

i18n/pt_PT/development/extension-packages.md

Hi translate this file, and I create also de file development/extension-packages.md

pt_PT translation of file extension-packages.md

---

i18n/pt_PT/development/hooks.md

Hi translate this file, and I create also de file development/hooks.md

pt_PT translation of file hooks.md

---

i18n/pt_PT/development/metadata.md

Hi translate this file, and I create also de file development/metadata.md

pt_PT translation of file metadata.md

---

i18n/pt_BR/development/how-to-create-a-dashlet.md

Hi translate this file, and I create also de file development/how-to-create-a-dashlet.md

pt_PT translation of file how-to-create-a-dashlet.md

---

i18n/sl-SI/administration/b2c.md
i18n/sl-SI/administration/email-fetching.md
i18n/sl-SI/administration/ldap-authorization-for-ad.md
i18n/sl-SI/administration/ldap-authorization-for-openldap.md
i18n/sl-SI/administration/workflows.md

Changes made:
1. b2c.md
2. email-fetching.md
3. ldap-authorization-for-ad.md
4. ldap-authorization-for-openldap.md
5. workflows.md

Slovenian Localization #5

---

i18n/pt_PT/development/new-function-in-formula.md

Hi translate this file, and I create also de file development/new-function-in-formula.md

pt_PT translation of file new-function-in-formula.md

---

i18n/pt_PT/development/link-multiple-with-primary.md

Hi translate this file, and I create also de file development/link-multiple-with-primary.md

pt_PT translation of file link-multiple-with-primary.md

---

i18n/pt_PT/scheduled-job.md

Hi translate this file, and I create also de file development/scheduled-job.md

pt_PT translation of file scheduled-job.md

---

i18n/pt_PT/development/workflow-service-actions.md

Hi translate this file, and I create also de file development/workflow-service-actions.md

pt_PT translation of file workflow-service-actions.md

---

i18n/pt_PT/development/orm.md

Hi translate this file, and I create also de file development/orm.md

pt_PT translation of file orm.md

---

i18n/hun_HUN/administration/emails.md

Hello ! My translation this article

hun_HUN traslation file emails.md (742 words)

---

i18n/tl_PH/README.md
i18n/tl_PH/user-guide/reports.md
i18n/tl_PH/user-guide/sales-management.md
i18n/tl_PH/user-guide/stream.md

Contents : 
README.md
User-guide files:
reports.md
sales-management.md
stream.md
Thank You

tl_PH Tagalog Translation [1403 WORDS] #1

---

i18n/ceb_PH/development/custom-field-type.md
i18n/ceb_PH/development/dynamic-forms.md
i18n/ceb_PH/user-guide/printing-to-pdf.md
i18n/ceb_PH/user-guide/reports.md

Changes made:
1. i18n/ceb_PH/development/custom-field-type.md
2. i18n/ceb_PH/development/dynamic-forms.md
3. i18n/ceb_PH/user-guide/printing-to-pdf.md
4. i18n/ceb_PH/user-guide/reports.md

Cebuano Localization #10

---

i18n/pt_BR/development/dynamic-forms.md

Hi translate this file, and I create also de file development/dynamic-forms.md

pt_BR translation of file dynamic-forms.md

---

i18n/pt_BR/development/extension-packages.md

Hi translate this file, and I create also de file development/extension-packages.md

pt_BR translation of file extension-packages.md

---

i18n/pt_BR/development/hooks.md

Hi translate this file, and I create also de file development/hooks.md

pt_BR translation of file hooks.md

---

i18n/pt_BR/development/link-multiple-with-primary.md

Hi translate this file, and I create also de file development/link-multiple-with-primary.md

pt_BR translation of file link-multiple-with-primary.md

---

i18n/pt_BR/development/metadata.md

Hi translate this file, and I create also de file development/metadata.md

pt_BR translation of file metadata.md

---

i18n/pt_BR/development/new-function-in-formula.md

Hi translate this file, and I create also de file development/new-function-in-formula.md

pt_BR translation of file new-function-in-formula.md

---

i18n/pt_BR/development/orm.md

Hi translate this file, and I create also de file development/orm.md

pt_BR translation of file orm.md

---

i18n/pt_BR/development/scheduled-job.md

Hi translate this file, and I create also de file development/scheduled-job.md

pt_BR translation of file scheduled-job.md

---

i18n/pt_BR/development/workflow-service-actions.md

Hi translate this file, and I create also de file development/workflow-service-actions.md

pt_BR translation of file workflow-service-actions.md

---

i18n/tl_PH/user-guide/printing-to-pdf.md
i18n/tl_PH/user-guide/quotes.md

Added to translated files from user-guide
-printing-to-pdf.md
-quotes.md
@yurikuzn

Tagalog Localization  Continuation # 2

---

i18n/tl_PH/administration/server-configuration.md
i18n/tl_PH/administration/troubleshooting.md
i18n/tl_PH/administration/workflows.md

Changes made:
Added Filipino (Tagalog) Translation Files to this directory:
1. i18n/tl_PH/administration/server-configuration.md
2. i18n/tl_PH/administration/troubleshooting.md
3. i18n/tl_PH/administration/workflows.md

Filipino (Tagalog) Localization #7

---

i18n/tl_PH/development/api.md
i18n/tl_PH/development/custom-field-type.md
i18n/tl_PH/development/custom-views.md
i18n/tl_PH/development/dynamic-forms.md
i18n/tl_PH/development/extension-packages.md
i18n/tl_PH/development/hooks.md
i18n/tl_PH/development/how-to-create-a-dashlet.md
i18n/tl_PH/development/link-multiple-with-primary.md
i18n/tl_PH/development/metadata.md
i18n/tl_PH/development/new-function-in-formula.md
i18n/tl_PH/development/orm.md
i18n/tl_PH/development/scheduled-job.md
i18n/tl_PH/development/workflow-service-actions.md
i18n/tl_PH/user-guide/activities-and-calendar.md
i18n/tl_PH/user-guide/browser-support.md
i18n/tl_PH/user-guide/case-management.md
i18n/tl_PH/user-guide/emails.md
i18n/tl_PH/user-guide/markdown.md
i18n/tl_PH/user-guide/mass-email.md

I already madea clone of all the files to  
https://github.com/cordeta/documentation/tree/master/i18n/tl_PH
particularly in this directories : 
https://github.com/cordeta/documentation/tree/master/i18n/tl_PH/development
https://github.com/cordeta/documentation/tree/master/i18n/tl_PH/user-guide
Thanks

tl_PH cloned files for fast translation

---

i18n/tl_PH/user-guide/emails.md
i18n/tl_PH/user-guide/markdown.md
i18n/tl_PH/user-guide/mass-email.md

Applied new translations : 
Affected file and location : 
mass-email.md  : 
https://github.com/espocrm/documentation/blob/master/i18n/tl_PH/user-guide/mass-email.md
markdown.md  :  
https://github.com/espocrm/documentation/blob/master/i18n/tl_PH/user-guide/markdown.md
emails.md :
https://github.com/espocrm/documentation/blob/master/i18n/tl_PH/user-guide/emails.md

Tagalog Localization # 3

---

i18n/tl_PH/development/api.md
i18n/tl_PH/development/custom-field-type.md
i18n/tl_PH/development/custom-views.md
i18n/tl_PH/development/dynamic-forms.md
i18n/tl_PH/development/extension-packages.md

Changes made:
Added Filipino (Tagalog) Translation Files to this directory:
1. i18n/tl_PH/development/api.md
2. i18n/tl_PH/development/custom-field-type.md
3. i18n/tl_PH/development/custom-views.md
4.  i18n/tl_PH/development/dynamic-forms.md
5. i18n/tl_PH/development/extension-packages.md

Filipino (Tagalog) Localization #8

---

i18n/sl-SI/administration/backup-and-restore.md
i18n/sl-SI/administration/formula.md
i18n/sl-SI/administration/import.md
i18n/sl-SI/administration/maps.md
i18n/sl-SI/administration/troubleshooting.md

Changes made:
1. formula.md
2. maps.md

Slovenian Localization #6

---

i18n/tl_PH/user-guide/activities-and-calendar.md
i18n/tl_PH/user-guide/browser-support.md
i18n/tl_PH/user-guide/case-management.md

Added New translated files : 
Files : 
activities-and-calendar.md
browser-support.md
case-management.md
Location : 
https://github.com/espocrm/documentation/blob/master/i18n/tl_PH/user-guide/case-management.md
https://github.com/espocrm/documentation/blob/master/i18n/tl_PH/user-guide/browser-support.md
https://github.com/espocrm/documentation/blob/master/i18n/tl_PH/user-guide/activities-and-calendar.md

Tagalog Localization # 4

---

i18n/sl-SI/administration/backup-and-restore.md
i18n/sl-SI/administration/import.md
i18n/sl-SI/administration/troubleshooting.md

Changes made:
1. backup-and-restore.md
2. import.md
3. troubleshooting.md

Slovenian Localization #7

---

i18n/ceb_PH/development/custom-views.md
i18n/ceb_PH/user-guide/activities-and-calendar.md
i18n/ceb_PH/user-guide/case-management.md
i18n/ceb_PH/user-guide/sales-management.md
i18n/tl_PH/development/api.md
i18n/tl_PH/development/extension-packages.md

Changes made:
Corrected translations in Filipino:
1. i18n/tl_PH/development/api.md
2. i18n/tl_PH/development/extension-packages.md
Added Cebuano Translation File to these directories:
1. i18n/ceb_PH/development/custom-views.md
2. i18n/ceb_PH/user-guide/activities-and-calendar.md
3. i18n/ceb_PH/user-guide/case-management.md
4. i18n/ceb_PH/user-guide/sales-management.md

Cebuano Localization #11

---

i18n/pl_PL/administration/server-configuration.md
i18n/pl_PL/administration/troubleshooting.md
i18n/pl_PL/administration/upgrading.md
i18n/pl_PL/development/custom-views.md
i18n/pl_PL/user-guide/stream.md

server-configuration
troubleshooting
upgrading
custom-views
stream

polish translation 1095 words administration, development and user-guide

---

i18n/ceb_PH/development/new-function-in-formula.md
i18n/ceb_PH/development/orm.md
i18n/ceb_PH/development/scheduled-job.md
i18n/ceb_PH/development/workflow-service-actions.md

Added Cebuano Translation Files to these directories:
1. i18n/ceb_PH/development/new-function-in-formula.md
2. i18n/ceb_PH/development/orm.md
3. i18n/ceb_PH/development/scheduled-job.md
4. i18n/ceb_PH/development/workflow-service-actions.md

Cebuano Localization #13

---

i18n/ceb_PH/administration/dynamic-logic.md
i18n/ceb_PH/development/workflow-service-actions.md

Added Cebuano translation file to this directory:
1. i18n/ceb_PH/administration/dynamic-logic.md
Updated Cebuano translation for this file:
1. i18n/ceb_PH/development/workflow-service-actions.md

Cebuano Localization #13 (Updated)

---

i18n/ceb_PH/development/api.md
i18n/ceb_PH/development/extension-packages.md
i18n/ceb_PH/development/hooks.md
i18n/ceb_PH/development/how-to-create-a-dashlet.md
i18n/ceb_PH/development/link-multiple-with-primary.md
i18n/ceb_PH/development/metadata.md

Added Cebuano Translation File to these directories:
1. i18n/ceb_PH/development/link-multiple-with-primary.md
2. i18n/ceb_PH/development/api.md
3. i18n/ceb_PH/development/extension-packages.md
4. i18n/ceb_PH/development/hooks.md
5. i18n/ceb_PH/development/how-to-create-a-dashlet.md
6. i18n/ceb_PH/development/metadata.md

Cebuano Localization #12

---

i18n/pt_PT/user-guide/activities-and-calendar.md

Hi translate this file, and I create also de file activities-and-calendar.md

pt_PT translation of file activities-and-calendar.md

---

i18n/pt_PT/user-guide/case-management.md

Hi translate this file, and I create also de file case-management.md

pt_PT translation of file case-management.md

---

i18n/pt_PT/user-guide/sales-management.md

Hi translate this file, and I create also de file: sales-management.md
I think this is the last file that has to be translated into Portuguese from this project.
Is there any other file to translate?
It was a pleasure to be part of this project, if you have any other projects to translate, just say

pt_PT translation of file: sales-management.md

---

i18n/pt_PT/user-guide/printing-to-pdf.md

Hi translate this file, and I create also de file: printing-to-pdf.md

pt_PT translation of file: printing-to-pdf.md

---

i18n/sl-SI/administration/ldap-authorization.md
i18n/sl-SI/administration/moving-to-another-server.md
i18n/sl-SI/administration/portal.md

Changes made:
1. ldap-authorization.md
2. moving-to-another-server.md
3. portal.md

Slovenian Localization #8

---

i18n/ceb_PH/README.md

Added Cebuano readme with links to all Cebuano .md files.

Cebuano Localization (Final)

---

i18n/pt_BR/user-guide/activities-and-calendar.md

Hi translate this file, and I create also de file: activities-and-calendar.md

activities-and-calendar.md translation to portuguese ptbr

---

i18n/pt_BR/user-guide/case-management.md

Hi translate this file, and I create also de file: case-management.md

case-management.md translation to portuguese ptbr

---

i18n/pt_BR/user-guide/printing-to-pdf.md

Hi translate this file, and I create also de file: printing-to-pdf.md

printing-to-pdf.md translation to portuguese ptbr

---

i18n/pt_BR/user-guide/sales-management.md

Hi translate this file, and I create also de file: sales-management.md

sales-management.md translation to portuguese ptbr

---

development/api-client-php.md

curl resource is unreachable after it's closed (line 143)

warning fix

---

i18n/ru_RU/README.md

Добавил ссылки и линки для:
- Расширения
- Динамические формы
- Управление Бизнес-Процессами
- Рабочие потоки
Пофыксил линку для:
- Управление макетами

Пофиксил линки

---

docs/development/api-client-rust.md
docs/development/api.md

This commit adds documentation & links to espocrm-rs, the Rust API client implementation.

Rust client implementation documentation & links

---

docs/development/api-client-rust.md

- Fix a typo
- Fixed the formatting of the list, in the official docs it didn't render properly

Fixed typo and changed list formatting

---

docs/administration/formula.md

Documentation - Formula

---

docs/administration/sms-sending
docs/administration/sms-sending.md

Create SMS Sending article

---

docs/administration/currency.md

Spelling Error Typo in Documents - Update currency.md

---

docs/administration/formula.md

Changed the name of record\fineOne function to record\findOne.

typo correction

---

docs/extensions/outlook-integration/email.md

Based on my experience of setting this up today, SSL option under IMAP worked whereas TLS option failed.

added a recommendation

---

docs/extensions/outlook-integration/setting-up.md

My outlook email account would not connect using the integration until the added step of granting admin consent to the API permissions.

Added a step to setting-up.md

---

docs/development/metadata/app-reactions.md

Typo app-reactions.md

---

docs/development/api-client-zig.md

Developed an API client in Zig language, source code at https://github.com/definitepotato/espocrmz and still actively developed. Adding docs for this library.

Add api-client-zig.md

---

docs/development/custom-entity-type.md

Fix custom entity example
